# ---------- Etapa de compilación ----------
FROM ubuntu:22.04 AS build

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
    && cmake --build build --parallel

# ---------- Etapa final (imagen liviana de ejecución) ----------
FROM ubuntu:22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    libstdc++6 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=build /app/build/allocation_simulator/allocation_sim ./bin/allocation_sim
#COPY --from=build /app/build/translation_simulator/translation_sim ./bin/translation_sim
COPY data/ ./data/
COPY --from=build /app/allocation_simulator/tests ./allocation_simulator/tests

ENV PATH="/app/bin:${PATH}"

CMD ["/bin/bash"]